# Autogenerated wrapper script for Clang_unified_jll for x86_64-linux-gnu-cxx11-llvm_version+15
export clang, clang_apply_replacements, clang_check, clang_format, clang_scan_deps, clang_tidy, libclang, libclang_cpp

using Zlib_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("Clang_unified")
JLLWrappers.@declare_library_product(libclang, "libclang.so.15")
JLLWrappers.@declare_library_product(libclang_cpp, "libclang-cpp.so.15jl")
JLLWrappers.@declare_executable_product(clang)
JLLWrappers.@declare_executable_product(clang_apply_replacements)
JLLWrappers.@declare_executable_product(clang_check)
JLLWrappers.@declare_executable_product(clang_format)
JLLWrappers.@declare_executable_product(clang_scan_deps)
JLLWrappers.@declare_executable_product(clang_tidy)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libLLVM_jll)
    JLLWrappers.@init_library_product(
        libclang,
        "lib/libclang.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libclang_cpp,
        "lib/libclang-cpp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        clang,
        "tools/clang",
    )

    JLLWrappers.@init_executable_product(
        clang_apply_replacements,
        "tools/clang-apply-replacements",
    )

    JLLWrappers.@init_executable_product(
        clang_check,
        "tools/clang-check",
    )

    JLLWrappers.@init_executable_product(
        clang_format,
        "tools/clang-format",
    )

    JLLWrappers.@init_executable_product(
        clang_scan_deps,
        "tools/clang-scan-deps",
    )

    JLLWrappers.@init_executable_product(
        clang_tidy,
        "tools/clang-tidy",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
