# Autogenerated wrapper script for Clang_unified_jll for x86_64-w64-mingw32-cxx11-llvm_version+20.asserts
export clang, clang_apply_replacements, clang_check, clang_format, clang_scan_deps, clang_tidy, libclang, libclang_cpp

using Zlib_jll
using Zstd_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("Clang_unified")
JLLWrappers.@declare_library_product(libclang, "libclang.dll")
JLLWrappers.@declare_library_product(libclang_cpp, "libclang-cpp.dll")
JLLWrappers.@declare_executable_product(clang)
JLLWrappers.@declare_executable_product(clang_apply_replacements)
JLLWrappers.@declare_executable_product(clang_check)
JLLWrappers.@declare_executable_product(clang_format)
JLLWrappers.@declare_executable_product(clang_scan_deps)
JLLWrappers.@declare_executable_product(clang_tidy)
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, Zstd_jll, libLLVM_jll)
    JLLWrappers.@init_library_product(
        libclang,
        "bin\\libclang.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libclang_cpp,
        "bin\\libclang-cpp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        clang,
        "tools\\clang.exe",
    )

    JLLWrappers.@init_executable_product(
        clang_apply_replacements,
        "tools\\clang-apply-replacements.exe",
    )

    JLLWrappers.@init_executable_product(
        clang_check,
        "tools\\clang-check.exe",
    )

    JLLWrappers.@init_executable_product(
        clang_format,
        "tools\\clang-format.exe",
    )

    JLLWrappers.@init_executable_product(
        clang_scan_deps,
        "tools\\clang-scan-deps.exe",
    )

    JLLWrappers.@init_executable_product(
        clang_tidy,
        "tools\\clang-tidy.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
